### ISSUE TITLE
Hi, Daniel Barath, how do you draw Figure 5 and Figure 6?

### ISSUE THREAD

**Issue by yangninghua** [danini/homography-from-sift-features#1]
![image](https://user-images.githubusercontent.com/32252319/67646649-1c68f180-f96a-11e9-9d00-3a23395ad743.png)

**Comment by danini** [comment]
Hi,

I generated it by running the same code which is uploaded on synthetically generated data described in the paper. :)

Best,
Daniel

**Comment by yangninghua** [comment]
Thank you for your excellent work.
